import { useMemo,useState } from 'react'
import { exercises } from '../data/exercises'
import type { ExercisePreference,UserProfile } from '../types'

export default function Library({profile,onPreference}:{profile:UserProfile;onPreference:(id:string,pref:ExercisePreference)=>void}){
  const [q,setQ]=useState(''),[pattern,setPattern]=useState('all'),[selected,setSelected]=useState<string|null>(null)
  const list=useMemo(()=>exercises.filter(e=>e.trainingTypes.includes(profile.trainingType)).filter(e=>pattern==='all'||e.movementPattern===pattern).filter(e=>`${e.nameEnglish} ${e.nameVietnamese??''} ${e.primaryMuscles.join(' ')}`.toLowerCase().includes(q.toLowerCase())).slice(0,80),[profile.trainingType,q,pattern])
  const ex=selected?exercises.find(x=>x.id===selected):undefined
  return <main className="page"><header><p className="eyebrow">THƯ VIỆN</p><h1>Bài tập</h1><p className="muted">Đánh dấu bài bạn thích hoặc không hợp. Lịch sau sẽ ưu tiên theo lựa chọn đó.</p></header><section className="card library-tools"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm tên bài hoặc nhóm cơ…"/><select value={pattern} onChange={e=>setPattern(e.target.value)}><option value="all">Tất cả kiểu vận động</option><option value="vertical_pull">Kéo dọc</option><option value="horizontal_pull">Kéo ngang</option><option value="horizontal_push">Đẩy ngang</option><option value="vertical_push">Đẩy dọc</option><option value="squat">Squat</option><option value="hinge">Gập hông</option><option value="lunge">Chân một bên</option><option value="core">Core</option></select></section>
    <section className="card library-list">{list.map(e=>{const pref=profile.exercisePreferences[e.id]??'neutral',available=e.equipment.every(x=>profile.equipment.includes(x)||x==='Ghế/bục'||x==='Điểm bám');return <div className="library-row" key={e.id}><button className="library-main" onClick={()=>setSelected(selected===e.id?null:e.id)}><div><b>{e.nameEnglish}</b><small>{e.nameVietnamese} · {e.primaryMuscles.join(', ')}</small></div><span>{available?'Có thể tập':'Thiếu dụng cụ'}</span></button><div className="preference-buttons"><button className={pref==='prefer'?'active':''} onClick={()=>onPreference(e.id,pref==='prefer'?'neutral':'prefer')}>Ưu tiên</button><button className={pref==='avoid'?'avoid active':''} onClick={()=>onPreference(e.id,pref==='avoid'?'neutral':'avoid')}>Không hợp</button></div>{selected===e.id&&<div className="exercise-detail-inline"><b>Cách làm</b><ol>{e.instructionsVietnamese.map((x,i)=><li key={i}>{x}</li>)}</ol><b>Lỗi hay gặp</b><ul>{e.commonMistakesVietnamese.map((x,i)=><li key={i}>{x}</li>)}</ul><p><b>Hít thở:</b> {e.breathingVietnamese}</p><p><b>Lưu ý:</b> {e.safetyNotesVietnamese}</p></div>}</div>})}</section></main>
}
