import { useState } from 'react'
import type { CardioPreference, Goal, SecondaryGoal, TrainingType, UIMode, UserProfile } from '../types'
import EquipmentPicker from './EquipmentPicker'
import ActivityPreferences from './ActivityPreferences'

const uid=()=>crypto.randomUUID?crypto.randomUUID():String(Date.now())
const defaultEquipment:Record<TrainingType,string[]>={calisthenics:['Pull-up Bar','Dip Bar'],home:['Dumbbell','Pull-up Bar','Dip Bar'],gym:['Pull-up Bar','Dip Bar','Barbell','Dumbbell','Bench','Adjustable Bench','Squat Rack','Cable Machine','Lat Pulldown','Leg Press','Leg Extension','Leg Curl','Chest Press','Shoulder Press Machine','Pec Deck','Row Machine','Cardio Machine']}
const goals:{id:Goal;name:string;desc:string}[]=[
  {id:'fat_loss',name:'Giảm mỡ + giữ cơ',desc:'Giữ sức mạnh trong lúc giảm cân.'},{id:'recomp',name:'Giảm mỡ + tăng cơ',desc:'Cân bằng giữa tăng cơ và kiểm soát cân nặng.'},{id:'hypertrophy',name:'Tăng cơ',desc:'Ưu tiên khối lượng tập vừa đến cao.'},{id:'strength',name:'Tăng sức mạnh',desc:'Tập trung hơn vào các bài chính.'},{id:'definition',name:'Siết / nét cơ',desc:'Giữ cơ và hỗ trợ giảm mỡ.'},{id:'fitness',name:'Khỏe toàn diện',desc:'Sức mạnh, core và thể lực cân bằng.'},{id:'skill',name:'Kỹ năng Calisthenics',desc:'Tăng dần các biến thể kỹ năng.'}
]
const secondary:{id:SecondaryGoal;name:string}[]=[{id:'pullup_10',name:'10 Pull-ups'},{id:'pushup_30',name:'30 Push-ups'},{id:'dip_20',name:'20 Dips'},{id:'l_sit_20',name:'L-sit 20 giây'},{id:'handstand',name:'Handstand'},{id:'pistol_squat',name:'Pistol Squat'}]
const cardioDefault:CardioPreference={enabled:false,modes:[],sessionsPerWeek:2,minutesByMode:{walk:30,run:20,jump_rope:15},avoidLegDays:true}

export default function Onboarding({onDone,onDemo}:{onDone:(p:UserProfile)=>void;onDemo:()=>void}){
  const [step,setStep]=useState(1),[type,setType]=useState<TrainingType>('calisthenics'),[uiMode,setUiMode]=useState<UIMode>('simple'),[goal,setGoal]=useState<Goal>('fitness'),[secondaryGoals,setSecondaryGoals]=useState<SecondaryGoal[]>([])
  const [days,setDays]=useState(3),[minutes,setMinutes]=useState(45),[trainingDays,setTrainingDays]=useState<number[]>([1,3,5]),[exp,setExp]=useState<UserProfile['experience']>('beginner')
  const [name,setName]=useState(''),[age,setAge]=useState<number|undefined>(),[height,setHeight]=useState<number|undefined>(),[weight,setWeight]=useState<number|undefined>(),[target,setTarget]=useState<number|undefined>()
  const [equipment,setEquipment]=useState<string[]>(defaultEquipment.calisthenics),[injuries,setInjuries]=useState<string[]>([]),[bench,setBench]=useState({pushup:0,pullup:0,dip:0,squat:0,plank:0}),[db,setDb]=useState({fixed:false,minKg:2,maxKg:20,stepKg:1}),[cardio,setCardio]=useState(cardioDefault)
  const chooseType=(t:TrainingType)=>{setType(t);setEquipment(defaultEquipment[t]);if(t==='gym'&&goal==='skill')setGoal('fitness')}
  const toggleDay=(d:number)=>setTrainingDays(trainingDays.includes(d)?trainingDays.filter(x=>x!==d):[...trainingDays,d].sort())
  const toggleInjury=(x:string)=>setInjuries(injuries.includes(x)?injuries.filter(v=>v!==x):[...injuries,x])
  const toggleSecondary=(id:SecondaryGoal)=>setSecondaryGoals(secondaryGoals.includes(id)?secondaryGoals.filter(x=>x!==id):[...secondaryGoals,id].slice(0,2))
  const finish=()=>{
    const chosen=[...trainingDays];for(const d of [1,2,3,4,5,6,0])if(chosen.length<days&&!chosen.includes(d))chosen.push(d)
    onDone({id:uid(),name:name.trim()||'Bạn',age,heightCm:height,weightKg:weight,targetWeightKg:target,trainingType:type,goal,secondaryGoals,uiMode,experience:exp,daysPerWeek:days,trainingDays:chosen.slice(0,days),sessionMinutes:minutes,activityLevel:'medium',equipment,dumbbell:type==='home'?db:undefined,benchmarks:{pushup:bench.pushup,pullup:bench.pullup,dip:bench.dip,bodyweight_squat:bench.squat,plank:bench.plank},injuries,cardio,exercisePreferences:{},unit:'kg',theme:'light',createdAt:new Date().toISOString()})
  }
  return <div className="onboarding-shell"><div className="brand"><div className="brand-mark">SW</div><div><b>Smart Workout Coach</b><span>Giáo án cá nhân · lưu trên thiết bị</span></div></div><div className="onboarding card">
    <div className="stepbar">{[1,2,3,4,5].map(n=><i key={n} className={n<=step?'active':''}/>)}</div>
    {step===1&&<><p className="eyebrow">BƯỚC 1/5</p><h1>Bạn tập ở đâu?</h1><div className="choice-grid"><button className={type==='calisthenics'?'choice selected':'choice'} onClick={()=>chooseType('calisthenics')}><b>Calisthenics</b><span>Xà đơn · xà kép · trọng lượng cơ thể</span></button><button className={type==='home'?'choice selected':'choice'} onClick={()=>chooseType('home')}><b>Tạ đơn tại nhà</b><span>Tạ đơn + xà, ít dụng cụ</span></button><button className={type==='gym'?'choice selected':'choice'} onClick={()=>chooseType('gym')}><b>Phòng Gym</b><span>Tạ đòn, máy tập, cáp và tạ đơn</span></button></div><h3 className="subheading">Mức chi tiết</h3><div className="mode-grid"><button className={uiMode==='simple'?'mode-card selected':'mode-card'} onClick={()=>setUiMode('simple')}><b>Đơn giản</b><span>Ít thuật ngữ, tập trung vào việc cần làm.</span></button><button className={uiMode==='advanced'?'mode-card selected':'mode-card'} onClick={()=>setUiMode('advanced')}><b>Nâng cao</b><span>Hiện thêm RIR và số liệu chi tiết.</span></button></div></>}
    {step===2&&<><p className="eyebrow">BƯỚC 2/5</p><h1>Mục tiêu</h1><div className="choice-grid compact">{goals.filter(g=>g.id!=='skill'||type!=='gym').map(g=><button key={g.id} className={goal===g.id?'choice selected':'choice'} onClick={()=>setGoal(g.id)}><b>{g.name}</b><span>{g.desc}</span></button>)}</div><h3 className="subheading">Mục tiêu phụ</h3><p className="muted">Không bắt buộc, tối đa 2.</p><div className="goal-chip-grid">{secondary.map(x=><button key={x.id} className={secondaryGoals.includes(x.id)?'goal-chip selected':'goal-chip'} onClick={()=>toggleSecondary(x.id)}><b>{x.name}</b></button>)}</div></>}
    {step===3&&<><p className="eyebrow">BƯỚC 3/5</p><h1>Lịch tuần</h1><label>Buổi sức mạnh mỗi tuần <strong>{days}</strong><input type="range" min="2" max="6" value={days} onChange={e=>setDays(+e.target.value)}/></label><label>Thời gian mỗi buổi</label><div className="chips">{[20,30,45,60,75,90].map(v=><button className={minutes===v?'chip active':'chip'} onClick={()=>setMinutes(v)} key={v}>{v}'</button>)}</div><label>Ngày thuận tiện</label><div className="chips">{['CN','T2','T3','T4','T5','T6','T7'].map((x,i)=><button className={trainingDays.includes(i)?'chip active':'chip'} key={x} onClick={()=>toggleDay(i)}>{x}</button>)}</div><div className="info">Nếu lỡ một buổi, lịch có thể đưa buổi đó sang ngày kế tiếp thay vì bỏ luôn.</div></>}
    {step===4&&<><p className="eyebrow">BƯỚC 4/5</p><h1>Khả năng và dụng cụ</h1><label>Kinh nghiệm</label><div className="chips wrap">{[['new','Chưa từng tập'],['beginner','< 6 tháng'],['intermediate','6–24 tháng'],['advanced','> 2 năm']].map(([v,n])=><button key={v} className={exp===v?'chip active':'chip'} onClick={()=>setExp(v as UserProfile['experience'])}>{n}</button>)}</div><div className="form-grid"><label>Tên hiển thị<input value={name} onChange={e=>setName(e.target.value)} placeholder="Không bắt buộc"/></label><label>Tuổi<input type="number" value={age??''} onChange={e=>setAge(e.target.value?+e.target.value:undefined)}/></label><label>Chiều cao (cm)<input type="number" value={height??''} onChange={e=>setHeight(e.target.value?+e.target.value:undefined)}/></label><label>Cân nặng (kg)<input type="number" step="0.1" value={weight??''} onChange={e=>setWeight(e.target.value?+e.target.value:undefined)}/></label><label>Mục tiêu cân nặng<input type="number" step="0.1" value={target??''} onChange={e=>setTarget(e.target.value?+e.target.value:undefined)}/></label></div><h3 className="subheading">Mốc hiện tại</h3><div className="form-grid"><label>Push-up tối đa<input type="number" min="0" value={bench.pushup} onChange={e=>setBench({...bench,pushup:+e.target.value})}/></label><label>Pull-up tối đa<input type="number" min="0" value={bench.pullup} onChange={e=>setBench({...bench,pullup:+e.target.value})}/></label><label>Dip tối đa<input type="number" min="0" value={bench.dip} onChange={e=>setBench({...bench,dip:+e.target.value})}/></label><label>Squat không tạ<input type="number" min="0" value={bench.squat} onChange={e=>setBench({...bench,squat:+e.target.value})}/></label><label>Plank (giây)<input type="number" min="0" value={bench.plank} onChange={e=>setBench({...bench,plank:+e.target.value})}/></label></div><h3 className="subheading">Dụng cụ</h3><EquipmentPicker type={type} value={equipment} onChange={setEquipment}/>{type==='home'&&<div className="subcard"><b>Tạ đơn</b><div className="form-grid"><label>Nhẹ nhất (kg)<input type="number" value={db.minKg} onChange={e=>setDb({...db,minKg:+e.target.value})}/></label><label>Nặng nhất (kg)<input type="number" value={db.maxKg} onChange={e=>setDb({...db,maxKg:+e.target.value})}/></label><label>Bước tăng (kg)<select value={db.stepKg} onChange={e=>setDb({...db,stepKg:+e.target.value})}>{[0.5,1,2,2.5,5].map(x=><option key={x}>{x}</option>)}</select></label></div></div>}<h3 className="subheading">Đau / hạn chế</h3><div className="chips wrap">{['Vai','Khuỷu tay','Cổ tay','Lưng dưới','Hông','Đầu gối','Cổ chân'].map(x=><button key={x} className={injuries.includes(x)?'chip danger active':'chip'} onClick={()=>toggleInjury(x)}>{x}</button>)}</div></>}
    {step===5&&<><p className="eyebrow">BƯỚC 5/5</p><h1>Vận động thêm</h1><p className="muted">Có thể ghép đi bộ, chạy hoặc nhảy dây vào cùng lịch. Không bắt buộc.</p><ActivityPreferences value={cardio} onChange={setCardio}/><div className="privacy-note">Dữ liệu chỉ nằm trên trình duyệt này. Có thể xuất file sao lưu trong Cài đặt.</div></>}
    <div className="actions"><button className="btn ghost" disabled={step===1} onClick={()=>setStep(Math.max(1,step-1))}>Quay lại</button>{step<5?<button className="btn primary" onClick={()=>setStep(step+1)}>Tiếp tục</button>:<button className="btn primary" onClick={finish}>Tạo giáo án</button>}</div>
  </div><button className="demo-link" onClick={onDemo}>Dùng thử Demo</button></div>
}
