import type { BodyMetric, WorkoutSession } from '../types'
import { personalRecords } from '../core/trainingEngine'
import { shortDate } from '../utils/date'
export default function Progress({sessions,metrics,onAddMetric}:{sessions:WorkoutSession[];metrics:BodyMetric[];onAddMetric:(m:BodyMetric)=>void}){
  const done=sessions.filter(s=>s.completedAt), prs=personalRecords(done).slice(0,8)
  const totalSets=done.reduce((n,s)=>n+s.exercises.reduce((a,e)=>a+e.sets.filter(x=>x.completed).length,0),0)
  const add=()=>{const w=prompt('Cân nặng hiện tại (kg), có thể bỏ trống:');const waist=prompt('Vòng eo (cm), có thể bỏ trống:');if(!w&&!waist)return;onAddMetric({id:crypto.randomUUID(),date:new Date().toISOString(),weightKg:w?+w:undefined,waistCm:waist?+waist:undefined})}
  return <main className="page"><header><p className="eyebrow">THEO DÕI THỰC TẾ</p><h1>Tiến độ</h1></header><section className="mini-grid"><div className="stat"><b>{done.length}</b><span>Buổi hoàn thành</span></div><div className="stat"><b>{totalSets}</b><span>Tổng hiệp</span></div><div className="stat"><b>{Math.round(done.reduce((n,s)=>n+(s.completionPct??0),0)/Math.max(1,done.length))}%</b><span>Tỷ lệ hoàn thành</span></div></section><section className="card"><div className="section-title"><h3>Kỷ lục cá nhân</h3></div>{prs.length?prs.map((r,i)=><div className="record" key={i}><b>{r.name}</b><span>{r.weight?`${r.weight} kg × `:''}{r.reps} lần</span></div>):<p className="muted">Hoàn thành vài buổi để app tạo kỷ lục cá nhân.</p>}</section><section className="card"><div className="section-title"><h3>Chỉ số cơ thể</h3><button className="text-btn" onClick={add}>+ Ghi số đo</button></div>{metrics.slice().reverse().slice(0,6).map(m=><div className="record" key={m.id}><b>{shortDate(m.date)}</b><span>{m.weightKg?`${m.weightKg} kg`:''}{m.weightKg&&m.waistCm?' · ':''}{m.waistCm?`Eo ${m.waistCm} cm`:''}</span></div>)}{!metrics.length&&<p className="muted">Không bắt buộc nhập cân nặng hoặc số đo.</p>}</section><section className="card"><h3>Lịch sử gần đây</h3>{done.slice().reverse().slice(0,10).map(s=><div className="history" key={s.id}><div><b>{s.title}</b><small>{shortDate(s.completedAt!)} · {s.exercises.length} bài</small></div><span>{s.completionPct}%</span></div>)}</section></main>
}
