import type { BodyMetric, UserProfile, WorkoutSession } from '../types'
import { personalRecords } from '../core/trainingEngine'
import { progressionFor, weeklySummary } from '../core/v2Insights'
import { shortDate } from '../utils/date'

export default function Progress({profile,sessions,metrics,onAddMetric}:{profile:UserProfile;sessions:WorkoutSession[];metrics:BodyMetric[];onAddMetric:(m:BodyMetric)=>void}){
  const done=sessions.filter(s=>s.completedAt), prs=personalRecords(done).slice(0,8)
  const totalSets=done.reduce((n,s)=>n+s.exercises.reduce((a,e)=>a+e.sets.filter(x=>x.completed).length,0),0)
  const week=weeklySummary(profile,sessions,metrics)
  const tracks=progressionFor(profile,sessions)
  const simple=(profile.uiMode??'simple')==='simple'
  const add=()=>{const w=prompt('Cân nặng hiện tại (kg), có thể bỏ trống:');const waist=prompt('Vòng eo (cm), có thể bỏ trống:');if(!w&&!waist)return;onAddMetric({id:crypto.randomUUID(),date:new Date().toISOString(),weightKg:w?+w:undefined,waistCm:waist?+waist:undefined})}
  return <main className="page"><header><p className="eyebrow">THEO DÕI THỰC TẾ</p><h1>Tiến độ</h1></header>
    <section className="weekly-card"><div className="section-title"><div><p className="eyebrow">7 NGÀY GẦN NHẤT</p><h3>Báo cáo tuần</h3></div><span className={week.sessions>=week.target?'status-good':'status-neutral'}>{week.sessions}/{week.target} buổi</span></div><div className="weekly-stats"><div><b>{week.sessions}</b><span>Buổi tập</span></div><div><b>{week.sets}</b><span>Hiệp hoàn thành</span></div><div><b>{week.minutes || '—'}</b><span>{week.minutes?'Phút tập':'Chưa đủ thời gian'}</span></div><div><b>{week.avgCompletion}%</b><span>Hoàn thành TB</span></div></div>{!simple&&week.prevSets>0&&<p className="muted">Khối lượng hiệp: {week.sets>week.prevSets?'+':''}{week.sets-week.prevSets} so với 7 ngày trước.</p>}<div className="coach-note"><b>HLV tự động nhận xét</b><p>{week.coach}</p></div></section>
    <section className="mini-grid"><div className="stat"><b>{done.length}</b><span>Buổi hoàn thành</span></div><div className="stat"><b>{totalSets}</b><span>Tổng hiệp</span></div><div className="stat"><b>{Math.round(done.reduce((n,s)=>n+(s.completionPct??0),0)/Math.max(1,done.length))}%</b><span>Tỷ lệ hoàn thành</span></div></section>
    {(profile.trainingType==='calisthenics'||profile.trainingType==='home')&&<section className="card"><div className="section-title"><div><h3>Bản đồ tiến bộ Calisthenics</h3><p className="muted">App đánh dấu cấp cao nhất bạn đã thực sự tập hoặc khai báo ở đầu vào.</p></div></div><div className="progression-tracks">{tracks.map(track=><div className="track" key={track.key}><div className="track-head"><b>{track.title}</b><span>{track.pct}%</span></div><div className="track-bar"><i style={{width:`${track.pct}%`}}/></div><div className="track-current">Hiện tại: <b>{track.current}</b>{track.next&&<span>Tiếp theo: {track.next}</span>}</div>{!simple&&<div className="track-steps">{track.steps.map(([id,name],i)=><span key={id} className={i===track.index?'current':i<track.index?'done':''}>{name}</span>)}</div>}</div>)}</div></section>}
    <section className="card"><div className="section-title"><h3>Kỷ lục cá nhân</h3></div>{prs.length?prs.map((r,i)=><div className="record" key={i}><b>{r.name}</b><span>{r.weight?`${r.weight} kg × `:''}{r.reps} lần</span></div>):<p className="muted">Hoàn thành vài buổi để app tạo kỷ lục cá nhân.</p>}</section>
    <section className="card"><div className="section-title"><h3>Chỉ số cơ thể</h3><button className="text-btn" onClick={add}>+ Ghi số đo</button></div>{metrics.slice().reverse().slice(0,6).map(m=><div className="record" key={m.id}><b>{shortDate(m.date)}</b><span>{m.weightKg?`${m.weightKg} kg`:''}{m.weightKg&&m.waistCm?' · ':''}{m.waistCm?`Eo ${m.waistCm} cm`:''}</span></div>)}{!metrics.length&&<p className="muted">Không bắt buộc nhập cân nặng hoặc số đo.</p>}</section>
    <section className="card"><h3>Lịch sử gần đây</h3>{done.slice().reverse().slice(0,10).map(s=><div className="history" key={s.id}><div><b>{s.title}</b><small>{shortDate(s.completedAt!)} · {s.exercises.length} bài</small></div><span>{s.completionPct}%</span></div>)}</section>
  </main>
}
