import { exerciseById } from '../data/exercises'
import { formatPace } from '../core/cardioEngine'
import { personalRecords } from '../core/trainingEngine'
import { plateauList,progressionFor,trainingAge,weeklySummary } from '../core/insights'
import { shortDate } from '../utils/date'
import type { ActivitySession,BodyMetric,UserProfile,WorkoutSession } from '../types'

export default function Progress({profile,sessions,activities,metrics,onAddMetric}:{profile:UserProfile;sessions:WorkoutSession[];activities:ActivitySession[];metrics:BodyMetric[];onAddMetric:(m:BodyMetric)=>void}){
  const done=sessions.filter(s=>s.completedAt),prs=personalRecords(done).slice(0,8),week=weeklySummary(profile,sessions,activities,metrics),age=trainingAge(profile,sessions,activities),plateaus=plateauList(sessions),tracks=progressionFor(profile,sessions),simple=profile.uiMode==='simple'
  const totalSets=done.reduce((n,s)=>n+s.exercises.reduce((a,e)=>a+e.sets.filter(x=>x.completed).length,0),0)
  const add=()=>{const w=prompt('Cân nặng hiện tại (kg), có thể bỏ trống:');const waist=prompt('Vòng eo (cm), có thể bỏ trống:');if(!w&&!waist)return;onAddMetric({id:crypto.randomUUID(),date:new Date().toISOString(),weightKg:w?+w:undefined,waistCm:waist?+waist:undefined})}
  return <main className="page"><header><p className="eyebrow">TIẾN ĐỘ</p><h1>Nhìn lại quá trình</h1></header>
    <section className="weekly-card"><div className="section-title"><div><p className="eyebrow">7 NGÀY GẦN NHẤT</p><h3>Tuần này</h3></div><span className={week.sessions>=week.target?'status-good':'status-neutral'}>{week.sessions}/{week.target} buổi sức mạnh</span></div><div className="weekly-stats"><div><b>{week.sets}</b><span>Hiệp</span></div><div><b>{week.minutes}</b><span>Phút sức mạnh</span></div><div><b>{week.cardio.distanceKm}</b><span>Km đi/chạy</span></div><div><b>{week.cardio.minutes}</b><span>Phút vận động</span></div></div><div className="coach-note"><b>Gợi ý tuần này</b><p>{week.note}</p></div></section>
    <section className="card"><div className="section-title"><div><h3>Thời gian đồng hành</h3><p className="muted">Tính từ ngày tạo hồ sơ hiện tại.</p></div><b>{age.months>0?`${age.months} tháng`:`${age.days} ngày`}</b></div><div className="mini-grid"><div className="stat"><b>{age.strengthSessions}</b><span>Buổi sức mạnh</span></div><div className="stat"><b>{age.activitySessions}</b><span>Buổi vận động</span></div><div className="stat"><b>{totalSets}</b><span>Tổng hiệp</span></div></div></section>
    {plateaus.length>0&&<section className="card plateau-card"><h3>Bài đang chững</h3><p className="muted">Không cần đổi ngay. Nếu vài buổi nữa vẫn đứng yên thì nên đổi biến thể hoặc giảm tải ngắn.</p>{plateaus.map(id=><div className="record" key={id}><b>{exerciseById.get(id)?.nameEnglish??id}</b><span>Đang theo dõi</span></div>)}</section>}
    {(profile.trainingType==='calisthenics'||profile.trainingType==='home')&&<section className="card"><h3>Bản đồ Calisthenics</h3><div className="progression-tracks">{tracks.map(track=><div className="track" key={track.key}><div className="track-head"><b>{track.title}</b><span>{track.pct}%</span></div><div className="track-bar"><i style={{width:`${track.pct}%`}}/></div><div className="track-current">Hiện tại: <b>{track.current}</b>{track.next&&<span>Tiếp theo: {track.next}</span>}</div>{!simple&&<div className="track-steps">{track.steps.map(([id,name],i)=><span key={id} className={i===track.index?'current':i<track.index?'done':''}>{name}</span>)}</div>}</div>)}</div></section>}
    <section className="card"><h3>Kỷ lục cá nhân</h3>{prs.length?prs.map(r=><div className="record" key={r.id}><b>{r.name}</b><span>{r.weight?`${r.weight} kg × `:''}{r.reps} lần</span></div>):<p className="muted">Tập vài buổi để bắt đầu có kỷ lục.</p>}</section>
    <section className="card"><div className="section-title"><h3>Chỉ số cơ thể</h3><button className="text-btn" onClick={add}>+ Ghi số đo</button></div>{metrics.slice().reverse().slice(0,6).map(m=><div className="record" key={m.id}><b>{shortDate(m.date)}</b><span>{m.weightKg?`${m.weightKg} kg`:''}{m.weightKg&&m.waistCm?' · ':''}{m.waistCm?`Eo ${m.waistCm} cm`:''}</span></div>)}{!metrics.length&&<p className="muted">Không bắt buộc nhập cân nặng hoặc số đo.</p>}</section>
    {activities.length>0&&<section className="card"><h3>Vận động gần đây</h3>{activities.slice().reverse().slice(0,8).map(a=><div className="history" key={a.id}><div><b>{a.mode==='walk'?'Đi bộ':a.mode==='run'?'Chạy bộ':'Nhảy dây'}</b><small>{shortDate(a.completedAt)} · {Math.round(a.durationSeconds/60)} phút{a.distanceKm!==undefined?` · ${a.distanceKm.toFixed(2)} km`:''}{a.jumpCount!==undefined?` · ${a.jumpCount} lần`:''}</small></div><span>{a.avgPaceSecPerKm?formatPace(a.avgPaceSecPerKm):a.effort?`${a.effort}/5`:'✓'}</span></div>)}</section>}
  </main>
}
