import { useState } from 'react'
import type { AppState,Goal,SecondaryGoal,UserProfile } from '../types'
import EquipmentPicker from './EquipmentPicker'
import ActivityPreferences from './ActivityPreferences'
import { equipmentInfo } from '../data/equipmentCatalog'

const goalNames:Record<Goal,string>={fat_loss:'Giảm mỡ + giữ cơ',recomp:'Giảm mỡ + tăng cơ',hypertrophy:'Tăng cơ',strength:'Tăng sức mạnh',definition:'Siết / nét cơ',fitness:'Khỏe toàn diện',skill:'Kỹ năng Calisthenics'}
const secondary:{id:SecondaryGoal;name:string}[]=[{id:'pullup_10',name:'10 Pull-ups'},{id:'pushup_30',name:'30 Push-ups'},{id:'dip_20',name:'20 Dips'},{id:'l_sit_20',name:'L-sit 20 giây'},{id:'handstand',name:'Handstand'},{id:'pistol_squat',name:'Pistol Squat'}]
export default function Settings({state,onBackup,onRestore,onReset,onProfile,onRebuild,onExitDemo}:{state:AppState;onBackup:()=>void;onRestore:(f:File)=>void;onReset:()=>void;onProfile:(p:UserProfile,recalc?:boolean)=>void;onRebuild:()=>void;onExitDemo:()=>void}){
  const p=state.profile,[equipmentOpen,setEquipmentOpen]=useState(false);if(!p)return null
  const toggleGoal=(id:SecondaryGoal)=>{const next=p.secondaryGoals.includes(id)?p.secondaryGoals.filter(x=>x!==id):[...p.secondaryGoals,id].slice(0,2);onProfile({...p,secondaryGoals:next},true)}
  const changeDays=(n:number)=>{const days=[...p.trainingDays];for(const d of [1,2,3,4,5,6,0])if(days.length<n&&!days.includes(d))days.push(d);onProfile({...p,daysPerWeek:n,trainingDays:days.slice(0,n)},true)}
  const preferred=Object.values(p.exercisePreferences).filter(x=>x==='prefer').length,avoided=Object.values(p.exercisePreferences).filter(x=>x==='avoid').length
  return <main className="page"><header><p className="eyebrow">CÀI ĐẶT</p><h1>{p.name}</h1></header>
    <section className="card"><h3>Cách hiển thị</h3><div className="seg mode-seg"><button className={p.uiMode==='simple'?'active':''} onClick={()=>onProfile({...p,uiMode:'simple'})}>Đơn giản</button><button className={p.uiMode==='advanced'?'active':''} onClick={()=>onProfile({...p,uiMode:'advanced'})}>Nâng cao</button></div><div className="seg"><button className={p.theme==='light'?'active':''} onClick={()=>onProfile({...p,theme:'light'})}>Sáng</button><button className={p.theme==='dark'?'active':''} onClick={()=>onProfile({...p,theme:'dark'})}>Tối</button></div></section>
    <section className="card"><h3>Kế hoạch chính</h3><label>Mục tiêu<select value={p.goal} onChange={e=>onProfile({...p,goal:e.target.value as Goal},true)}>{(Object.keys(goalNames) as Goal[]).filter(g=>g!=='skill'||p.trainingType!=='gym').map(g=><option key={g} value={g}>{goalNames[g]}</option>)}</select></label><label>Số buổi sức mạnh <strong>{p.daysPerWeek}/tuần</strong><input type="range" min="2" max="6" value={p.daysPerWeek} onChange={e=>changeDays(+e.target.value)}/></label><label>Thời gian mỗi buổi<select value={p.sessionMinutes} onChange={e=>onProfile({...p,sessionMinutes:+e.target.value},true)}>{[20,30,45,60,75,90].map(x=><option key={x} value={x}>{x} phút</option>)}</select></label><button className="btn secondary full" onClick={onRebuild}>Tính lại giáo án ngay</button></section>
    <section className="card"><h3>Vận động thêm</h3><ActivityPreferences value={p.cardio} onChange={cardio=>onProfile({...p,cardio},true)}/></section>
    <section className="card"><div className="section-title"><div><h3>Dụng cụ</h3><p className="muted">Thay đổi ở đây sẽ tính lại bài tập.</p></div><button className="text-btn" onClick={()=>setEquipmentOpen(!equipmentOpen)}>{equipmentOpen?'Thu gọn':'Chỉnh sửa'}</button></div>{!equipmentOpen?<div className="equipment-summary">{p.equipment.map(k=><span key={k}>{equipmentInfo(k).vi}</span>)}</div>:<EquipmentPicker type={p.trainingType} value={p.equipment} onChange={equipment=>onProfile({...p,equipment},true)}/>}</section>
    <section className="card"><h3>Mục tiêu phụ</h3><div className="goal-chip-grid settings-goals">{secondary.map(x=><button key={x.id} className={p.secondaryGoals.includes(x.id)?'goal-chip selected':'goal-chip'} onClick={()=>toggleGoal(x.id)}><b>{x.name}</b></button>)}</div></section>
    <section className="card"><div className="section-title"><div><h3>Sở thích bài tập</h3><p className="muted">{preferred} bài ưu tiên · {avoided} bài không hợp</p></div>{preferred+avoided>0&&<button className="text-btn" onClick={()=>onProfile({...p,exercisePreferences:{}},true)}>Xoá lựa chọn</button>}</div><p className="muted">Chỉnh từng bài trong tab Thư viện.</p></section>
    <section className="card"><h3>Sao lưu</h3><button className="btn secondary full" onClick={onBackup}>Xuất Backup JSON</button><label className="btn secondary full file-btn">Nhập Backup 1.0<input type="file" accept="application/json" onChange={e=>e.target.files?.[0]&&onRestore(e.target.files[0])}/></label></section>
    {state.demoMode&&<button className="btn secondary full" onClick={onExitDemo}>Thoát Demo và tạo hồ sơ thật</button>}<button className="btn danger-btn full" onClick={onReset}>Xoá toàn bộ dữ liệu trên thiết bị này</button>
  </main>
}
